### ISSUE TITLE
More testing notes

### ISSUE THREAD

**Issue by glattercj** [activeshadow/minimega#16]
# Testing notes

## phenix config ...
- [x] `delete topology/helloworld`
  - if topology/helloworld doesn't exist, have a better error message for user? (see first item in `Misc`)

      ```bash
			Error: Unable to delete the topology/helloworld configuration (search error logs for 398f4e83-82a8-45ae-8330-7eb37bef8012)
      ```
- [x] `list`
  - Can we default to 'all' if no arg is specified after 'list'?

## phenix image ...
- [x] `create ...`
  - not exactly sure how the second one got parsed correctly:

      ```bash
      phenix image create -O /tmp/overlays/foo,/tmp/overlays/bar,/tmp/overlays/baz -T /tmp/scripts/foo --mirror=http://my.mirror.com --debootstrap-append="--components=main --no-check-gpg" --variant brash --format qcow2 -c foo
      ```

      ```bash
      phenix image create -O foo bar baz -s foo --mirror=http://my.mirror.com --debootstrap-append="--components=main --no-check-gpg" --variant brash --format qcow2 -c TEST
      ```

      ```bash
      root@test:/root# phenix image list
      +-------+-------+---------+---------+---------------------------------------+-----------------------+-----------------------------+
      | NAME  | SIZE  | VARIANT | RELEASE |               OVERLAYS                |       PACKAGES        |           SCRIPTS           |
      +-------+-------+---------+---------+---------------------------------------+-----------------------+-----------------------------+
      | foo   | 5G    | brash   | bionic  | /tmp/overlays/foo                     | initramfs-tools       | POSTBUILD_BRASH             |
      |       |       |         |         | /tmp/overlays/bar                     | net-tools             | POSTBUILD_NO_ROOT_PASSWD    |
      |       |       |         |         | /tmp/overlays/baz                     | isc-dhcp-client       | POSTBUILD_PHENIX_HOSTNAME   |
      |       |       |         |         |                                       | openssh-server        | /tmp/scripts/foo            |
      |       |       |         |         |                                       | init iputils-ping     | POSTBUILD_APT_CLEANUP       |
      |       |       |         |         |                                       | vim less netbase      |                             |
      |       |       |         |         |                                       | curl ifupdown dbus    |                             |
      |       |       |         |         |                                       | linux-image-generic   |                             |
      |       |       |         |         |                                       | linux-headers-generic |                             |
      |       |       |         |         |                                       | vsftpd socat telnet   |                             |
      |       |       |         |         |                                       | ftp pv python3        |                             |
      | brash | foo   | brash   | bionic  | foo                                   | initramfs-tools       | POSTBUILD_PHENIX_HOSTNAME   |
      |       |       |         |         |                                       | net-tools             | POSTBUILD_APT_CLEANUP       |
      |       |       |         |         |                                       | isc-dhcp-client       | POSTBUILD_BRASH             |
      |       |       |         |         |                                       | openssh-server        | POSTBUILD_NO_ROOT_PASSWD    |
      |       |       |         |         |                                       | init iputils-ping     |                             |
      |       |       |         |         |                                       | vim less netbase      |                             |
      |       |       |         |         |                                       | curl ifupdown dbus    |                             |
      |       |       |         |         |                                       | linux-image-generic   |                             |
      |       |       |         |         |                                       | linux-headers-generic |                             |
      |       |       |         |         |                                       | vsftpd socat telnet   |                             |
      |       |       |         |         |                                       | ftp pv python3        |                             |
      +-------+-------+---------+---------+---------------------------------------+-----------------------+-----------------------------+
      ```
- [x] `update -h`
  - Fix wording in help:

      ```bash
      root@test:/root# phenix image update -h
        ...

        Used to remove scripts, packages, and/or overlays to an existing virtual disk
        image configuration

        ...
      ```
- [x] `build ...`
  - phenix seems blocked while building an image (start building an image in 1 terminal, and in another, try to run `phenix image list`)

## Misc
- [x] Can you just print the same error in the log file and stdout, rather than having to see a not-very-useful message, and then having to redo the same command with `-V`?
	- rather than: `Error: Unable to create the foobar experiment (search error logs for 1acd8945-3b27-4c28-9558-8a6fa08f8598)`

  ```bash
  root@test:/root# phenix exp start helloworld --dry-run
  Error: Unable to start the helloworld experiment (search error logs for 38c693e0-dc47-438e-82a2-11ff3c79b9df)
  root@test:/root# phenix exp start helloworld --dry-run -V
  phenix2020/09/08 09:41:22 [c2014bac-9052-471c-8cfd-009cf7705f27] getting experiment helloworld from store: getting config: key helloworld does not exist in bucket Experiment
  Error: Unable to start the helloworld experiment (search error logs for c2014bac-9052-471c-8cfd-009cf7705f27)
	```
	- how about: `Error: experiment 'helloworld' does not exist`
	- or: `Error: Unable to create the 'foobar' experiment: host 'host-00' in app 'protonuke' not in topology`

- [x] What is the `-C, --config.file string` flag used for?
- [x] panic (can phenix automagically do the cfg creation by passing absolute paths to `exp create ...` and use the filename as the cfg name?):

	```bash
	root@test:/root# phenix experiment create foobar -t helloworld -s /tmp/scenario.yml
	panic: runtime error: invalid memory address or nil pointer dereference
	[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x82afc6]

	goroutine 1 [running]:
	phenix/store.BoltDB.Get(0xc00002c200, 0x0, 0x97fb00, 0xc0001975f0)
	        phenix@/store/bolt.go:85 +0x26
	phenix/store.Get(...)
	        phenix@/store/package.go:38
	phenix/api/experiment.Create(0x7ffdaff92e08, 0x6, 0x7ffdaff92e12, 0xa, 0x7ffdaff92e20, 0x14, 0x0, 0x0, 0xc00010f800, 0xc0001b3d60)
	        phenix@/api/experiment/experiment.go:123 +0x71e
	phenix/cmd.newExperimentCreateCmd.func1(0xc0001b8b00, 0xc000132c30, 0x1, 0x5, 0x0, 0x0)
	        phenix@/cmd/experiment.go:125 +0x178
	github.com/spf13/cobra.(*Command).execute(0xc0001b8b00, 0xc000132be0, 0x5, 0x5, 0xc0001b8b00, 0xc000132be0)
	        github.com/spf13/cobra@v1.0.0/command.go:842 +0x460
	github.com/spf13/cobra.(*Command).ExecuteC(0xec5320, 0x0, 0x0, 0x0)
	        github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
	github.com/spf13/cobra.(*Command).Execute(...)
	        github.com/spf13/cobra@v1.0.0/command.go:887
	phenix/cmd.Execute()
	        phenix@/cmd/root.go:53 +0x2d
	main.main()
	        phenix@/main.go:6 +0x20
	```
- [x] Inconsistent error messages...

  ```bash
  root@test:/root# phenix vm info
  Error: Must provide an experiment name
  ```

  ```bash
  root@test:/root# phenix cfg create
  Error: requires at least 1 arg(s), only received 0
  ```

  ```bash
  root@test:/root# phenix image create
  Error: Must provide an image name
  ```

- [x] Inconsistent arg usage ('exp/vm' vs 'exp vm')...

  ```bash
  root@test:/root# phenix vm info foobar/test1
  +------------+----------------------------------------------------------------------------------------------------+
  |  SETTING   |                                               VALUE                                                |
  +------------+----------------------------------------------------------------------------------------------------+
  | Host       | node1                                                                                              |
  | Name       | test1                                                                                              |
  | Running    | true                                                                                               |
  | Disk       | debian7.qc2                                                                                        |
  | Interfaces | ID: 0, IP: 192.168.1.1, VLAN: SW1 (101)                                                            |
  | Uptime     | 11m42s                                                                                             |
  | VCPUs      | 1                                                                                                  |
  | Memory     | 512                                                                                                |
  | OS Type    | linux                                                                                              |
  | Metadata   | {                                                                                                  |
  |            |   "protonuke": {                                                                                   |
  |            |     "args": "-logfile /var/log/protonuke.log -level debug -http -https -smtp -ssh 192.168.100.100" |
  |            |   }                                                                                                |
  |            | }                                                                                                  |
  +------------+----------------------------------------------------------------------------------------------------+
  ```

  ```bash
  root@test:/root# phenix vm pause foobar test2
  The test2 VM in the foobar experiment was paused
  ```

**Comment by dnkcom** [comment]
- Unable to reproduce `image build` seeming to lock up phenix. Believe fixed due to seeing this in other spots.
- `-C` global flag was removed.

**Comment by activeshadow** [comment]
@glattercj for the error message issue(s) mentioned above, is defaulting logging errors to stderr to true sufficient? Right now that defaults to false, so you have to provide the `-V` flag.

**Comment by glattercj** [comment]
@activeshadow Defaulting to true is fine for now. We can re-visit if necessary after we have a wider testing audience.

**Comment by activeshadow** [comment]
@glattercj the `issue-16` branch has been updated to address all the above noted issues.

**Comment by glattercj** [comment]
@activeshadow On the "inconsistent arg usage", the args are now consistent, but now one of them panics if you try and use a slash, while the other throws a normal error (exp `helloworld` is currently running...):

```bash
root@test:/root# phenix vm pause helloworld/test1
Error: Must provide an experiment and VM name
root@test:/root# phenix vm info helloworld/test1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xb505b0]

goroutine 1 [running]:
phenix/store.(*BoltDB).Get(0xc000345da0, 0x0, 0x0, 0x0)
        phenix/store/bolt.go:111 +0x70
phenix/store.Get(...)
        phenix/store/package.go:40
phenix/api/experiment.Get(0x7ffdace59e27, 0x10, 0x19fa8c0, 0x7fb20f59b108, 0x0)
        phenix/api/experiment/experiment.go:66 +0xb3
phenix/api/vm.List(0x7ffdace59e27, 0x10, 0xc0003d1f18, 0xc000424c40, 0xc0003adcb8, 0xb8213b, 0xe03120)
        phenix/api/vm/vm.go:48 +0x59
phenix/cmd.newVMInfoCmd.func1(0xc0003e9600, 0xc0003ccf90, 0x1, 0x1, 0x0, 0x0)
        phenix/cmd/vm.go:43 +0x28f
github.com/spf13/cobra.(*Command).execute(0xc0003e9600, 0xc0003ccf60, 0x1, 0x1, 0xc0003e9600, 0xc0003ccf60)
        github.com/spf13/cobra@v1.0.0/command.go:842 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0x19ec7e0, 0x0, 0x0, 0x0)
        github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.0.0/command.go:887
phenix/cmd.Execute()
        phenix/cmd/root.go:65 +0x2d
main.main()
        command-line-arguments/main.go:6 +0x20
```

**Comment by glattercj** [comment]
## phenix exp ...
- [ ] `delete all`
- [ ] `restart all`
  - keyword `all` exists for `start, stop`, but not for `restart,delete`
      ```bash
			root@test:/root# phenix exp delete all
                        phenix2020/09/25 12:46:02 [fc9d408b-dd2a-4ba5-873d-e4f3c1561ce1] getting experiment all from store: getting config: key all does not exist in bucket Experiment
                        Error: Unable to get the all experiment (search error logs for fc9d408b-dd2a-4ba5-873d-e4f3c1561ce1)
      ```

__*Should probably make sure users are disallowed from creating an exp called `all` because of this...*__

**Comment by activeshadow** [comment]
@glattercj we couldn't reproduce the namespace not getting cleared issue you mentioned above.
